#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake
wmake SRFPimpleFoam
wmake pimpleDyMFoam
wmake porousMRFPimpleFoam

# ----------------------------------------------------------------- end-of-file
